### ISSUE TITLE
Prefix Management

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/owltools2-experimental#9]
The IOHelper class should create a PrefixManager to help parse and render ontologies. It should include a good default set of prefixes so that further configuration is rarely required. We'll need at least these:

- rdf
- rdfs
- xsd
- owl
- obo

RDFa and JSON-LD define a larger set of default prefixes, and we could follow their lead (plus obo): http://www.w3.org/2011/rdfa-context/rdfa-1.1

I tend to use this style in my work: `obo:OBI_0000070`. So including the `obo` prefix covers all OBO ontologies.

In the Gene Ontology world there seems to be wide use of project-specific prefixes: `GO:0008150`, `UBERON:0001062`. Do we want to support this style? If so, how should we build the list of prefixes?

**Comment by jamesaoverton** [comment]
Here's a first pass at a JSON-LD file with common prefixes and prefixes for every OBO project:

https://github.com/ontodev/owltools2-experimental/blob/master/owltools2-core/src/main/resources/obo_context.jsonld

So far I've tested it at on the [JSON-LD playground](http://json-ld.org/playground/index.html) and it's seems to work as expected.

I'd like this to be a comprehensive default, so let me know if I've missed anything important.

The rest of the commit parses the JSON-LD into a map of prefixes, then loads those into an OWLAPI PrefixManager.

**Comment by cmungall** [comment]
Any prefix that itself includes an underscore is potentially ambiguous 
in the reverse translation. I think we're OK just now but something to 
be aware of. I think we wouldn't allow new ones now

Hmm, vHOG should really be VHOG (but not a big deal now VHOG was 
superseded by UBERON)

**Comment by jamesaoverton** [comment]
We're now using the [JSON-LD Java](https://github.com/jsonld-java/jsonld-java) library to parse contexts, then build an OWL PrefixManager/ShortFormProvider. These are the command-line options I have in mind for controlling prefixes:

0. no prefix options: use the default prefixes from [`obo_context.jsonld`](https://github.com/ontodev/owltools2-experimental/blob/master/owltools2-core/src/main/resources/obo_context.jsonld)
1. `--no-prefixes` do not use the default prefixes
2. `--prefixes FILE` (`-P FILE`) use your own JSON-LD file instead of the default prefixes
3. `--prefix "foo: http://foo.com#"` (`-p PREFIX`) add one prefix to the current set of prefixes (may be used multiple times); this should be convenient for projects that have not yet requested an OBO namespace

The `--prefixes` option will override the `--no-prefixes` option (it doesn't make sense to use them together). The `--prefixes` option can only be used once (I think that Apache CLI will take the first). There may be multiple `--prefix` options, and they will be added after the choice is made between the defaults, `--no-prefixes`, and the user's `--prefixes` file.

If you use `--prefixes`, your JSON-LD file should have a `@context` key. Otherwise you'll get an empty set of prefixes. The JSON-LD library should try to fetch external contexts. I haven't tested that yet, and it opens the doors to network failures and other unexpected behaviour, but it's an advanced option.

The command-line tool allows multiple subcommands. If the prefix options come before all subcommands, then they are global options that apply to all subcommands. If they come after a subcommand then they only apply to that subcommand. This is our general option scoping rule for subcommands.

This is a little more complicated than I would like, but it's fully configurable, and I think it all follows the principle of least surprise.

**Comment by jamesaoverton** [comment]
As I was sitting down to implement this, I noticed that a piece is missing. We should be able to write the current prefixes to a file (or print to console). This will also enable integration testing.

So I plan to add a `export-prefixes` command that will write JSON-LD. (The name is clumsy, but I like to start every command name with a verb. The verb could be "show" or "write" instead of "export".) If needed, we can add Turtle and SPARQL formats.

**Comment by cmungall** [comment]
`{export,dump}-prefixes` OK with me

**Comment by jamesaoverton** [comment]
Had to use `--noprefixes` instead of `--no-prefixes` because of Apache CLI option parsing rules.

Closed by commit 6153ee7
